package com.example.flaggameandroid.feature.app

internal val localizedContinentNames: Map<AppLanguage, Map<String, String>> =
  mapOf(
    AppLanguage.English to
      mapOf(
        "Africa" to "Africa",
        "Antarctica" to "Antarctica",
        "Asia" to "Asia",
        "Europe" to "Europe",
        "North America" to "North America",
        "Oceania" to "Oceania",
        "South America" to "South America",
      ),
    AppLanguage.Bulgarian to
      mapOf(
        "Africa" to "Африка",
        "Antarctica" to "Антарктида",
        "Asia" to "Азия",
        "Europe" to "Европа",
        "North America" to "Северна Америка",
        "Oceania" to "Океания",
        "South America" to "Южна Америка",
      ),
    AppLanguage.German to
      mapOf(
        "Africa" to "Afrika",
        "Antarctica" to "Antarktis",
        "Asia" to "Asien",
        "Europe" to "Europa",
        "North America" to "Nordamerika",
        "Oceania" to "Ozeanien",
        "South America" to "Südamerika",
      ),
  )

internal val localizedCountryAliases: Map<AppLanguage, Map<String, List<String>>> =
  mapOf(
    AppLanguage.Bulgarian to
      mapOf(
        "US" to listOf("САЩ", "Съединени американски щати", "Съединени щати"),
        "GB" to listOf("Великобритания", "Обединено кралство"),
        "AE" to listOf("ОАЕ", "Обединени арабски емирства"),
        "BA" to listOf("Босна и Херцеговина"),
        "CI" to listOf("Кот д'Ивоар", "Кот д Ивоар"),
        "CZ" to listOf("Чехия", "Чешка република"),
        "CD" to listOf("ДР Конго", "Демократична република Конго"),
        "CG" to listOf("Конго", "Република Конго"),
        "DO" to listOf("Доминиканска република"),
        "FM" to listOf("Микронезия"),
        "IR" to listOf("Иран"),
        "KP" to listOf("Северна Корея"),
        "KR" to listOf("Южна Корея"),
        "LA" to listOf("Лаос"),
        "MD" to listOf("Молдова"),
        "PS" to listOf("Палестина"),
        "RU" to listOf("Русия"),
        "SY" to listOf("Сирия"),
        "TZ" to listOf("Танзания"),
        "VA" to listOf("Ватикан"),
        "VE" to listOf("Венецуела"),
        "VN" to listOf("Виетнам"),
      ),
    AppLanguage.German to
      mapOf(
        "US" to listOf("USA", "Vereinigte Staaten von Amerika", "Vereinigte Staaten"),
        "GB" to listOf("Großbritannien", "Vereinigtes Königreich"),
        "AE" to listOf("VAE", "Vereinigte Arabische Emirate"),
        "BA" to listOf("Bosnien und Herzegowina"),
        "CI" to listOf("Elfenbeinküste", "Cote d Ivoire", "Côte d'Ivoire"),
        "CZ" to listOf("Tschechien", "Tschechische Republik"),
        "CD" to listOf("DR Kongo", "Demokratische Republik Kongo"),
        "CG" to listOf("Kongo", "Republik Kongo"),
        "DO" to listOf("Dominikanische Republik"),
        "FM" to listOf("Mikronesien"),
        "KP" to listOf("Nordkorea"),
        "KR" to listOf("Südkorea"),
        "MD" to listOf("Moldau", "Republik Moldau"),
        "PS" to listOf("Palästina"),
        "RU" to listOf("Russland"),
        "SY" to listOf("Syrien"),
        "TZ" to listOf("Tansania"),
        "VA" to listOf("Vatikan", "Vatikanstadt"),
        "VE" to listOf("Venezuela"),
        "VN" to listOf("Vietnam"),
      ),
    AppLanguage.English to emptyMap(),
  )

internal val localizedCapitalAliases: Map<AppLanguage, Map<String, String>> =
  mapOf(
    AppLanguage.Bulgarian to
      mapOf(
        "Vienna" to "Виена",
        "Brussels" to "Брюксел",
        "Prague" to "Прага",
        "Copenhagen" to "Копенхаген",
        "Athens" to "Атина",
        "Rome" to "Рим",
        "Warsaw" to "Варшава",
        "Bucharest" to "Букурещ",
        "Moscow" to "Москва",
        "Kyiv" to "Киев",
        "Nicosia" to "Никозия",
        "Budapest" to "Будапеща",
        "Belgrade" to "Белград",
        "Zagreb" to "Загреб",
        "Ljubljana" to "Любляна",
        "Amsterdam" to "Амстердам",
        "Bern" to "Берн",
        "Lisbon" to "Лисабон",
        "Paris" to "Париж",
        "London" to "Лондон",
        "Ottawa" to "Отава",
        "Canberra" to "Канбера",
        "Tokyo" to "Токио",
        "Seoul" to "Сеул",
        "Beijing" to "Пекин",
        "Peking" to "Пекин",
        "Madrid" to "Мадрид",
        "Stockholm" to "Стокхолм",
        "Helsinki" to "Хелзинки",
        "Reykjavik" to "Рейкявик",
        "Wellington" to "Уелингтън",
        "Washington D.C." to "Вашингтон, Д.К.",
        "Vatican City" to "Ватикана",
      ),
    AppLanguage.German to
      mapOf(
        "Vienna" to "Wien",
        "Brussels" to "Brüssel",
        "Prague" to "Prag",
        "Copenhagen" to "Kopenhagen",
        "Athens" to "Athen",
        "Rome" to "Rom",
        "Warsaw" to "Warschau",
        "Bucharest" to "Bukarest",
        "Moscow" to "Moskau",
        "Kyiv" to "Kiew",
        "Nicosia" to "Nikosia",
        "Peking" to "Peking",
        "Beijing" to "Peking",
        "Bratislava" to "Bratislava",
        "The Hague" to "Den Haag",
        "Washington D.C." to "Washington, D.C.",
        "Vatican City" to "Vatikanstadt",
        "Kuala Lumpur" to "Kuala Lumpur",
        "Seoul" to "Seoul",
        "Tokyo" to "Tokio",
        "Madrid" to "Madrid",
        "Lisbon" to "Lissabon",
        "Budapest" to "Budapest",
        "Stockholm" to "Stockholm",
        "Helsinki" to "Helsinki",
        "Riga" to "Riga",
        "Vilnius" to "Vilnius",
        "Tallinn" to "Tallinn",
        "Belgrade" to "Belgrad",
        "Zagreb" to "Zagreb",
        "Ljubljana" to "Ljubljana",
        "Sarajevo" to "Sarajevo",
        "Skopje" to "Skopje",
        "Sofia" to "Sofia",
        "Tirana" to "Tirana",
        "Podgorica" to "Podgorica",
        "Podgorica" to "Podgorica",
        "Valletta" to "Valletta",
        "Nicosia" to "Nikosia",
        "Andorra la Vella" to "Andorra la Vella",
        "Bucharest" to "Bukarest",
        "Chișinău" to "Chișinău",
        "Luxembourg" to "Luxemburg",
        "Bern" to "Bern",
        "Paris" to "Paris",
        "London" to "London",
        "Ottawa" to "Ottawa",
        "Canberra" to "Canberra",
        "Washington D.C." to "Washington, D.C.",
        "Brasília" to "Brasília",
      ),
    AppLanguage.English to emptyMap(),
  )

internal val secondaryCapitalAnswersByCountryCode: Map<String, List<String>> =
  mapOf(
    "BJ" to listOf("Cotonou"),
    "BO" to listOf("La Paz"),
    "BI" to listOf("Bujumbura"),
    "CI" to listOf("Abidjan"),
    "SZ" to listOf("Lobamba"),
    "MY" to listOf("Putrajaya"),
    "NL" to listOf("The Hague", "Den Haag"),
    "ZA" to listOf("Cape Town", "Bloemfontein"),
    "LK" to listOf("Sri Jayawardenepura Kotte", "Kotte"),
    "TZ" to listOf("Dar es Salaam"),
    "YE" to listOf("Aden"),
    "PS" to listOf("East Jerusalem", "Jerusalem"),
    "GQ" to listOf("Malabo"),
  )
